[package]
name = "subslay"
version = "0.1.8"
edition = "2021"
authors = ["AndriaK <hey@andriaK.com>"]
description = "SubSlay: Text â†’ emoji ğŸ’…ğŸ» Powered by Rust."
license = "MIT"
repository = "https://github.com/8ria/subslay"
readme = "README.md"
keywords = ["emoji", "text", "emoji-mapping", "natural-language"]
categories = ["text-processing", "command-line-utilities"]
include = [
  "src/**",
  "data/emoji.txt",
  "data/glove.txt",
  "Cargo.toml",
  "README.md",
]

[dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = 3
lto = true
