[package]
name = "subslay"
version = "0.1.9"
edition = "2021"
authors = ["AndriaK <hey@andriaK.com>"]
description = "SubSlay: Text â†’ emoji ğŸ’…ğŸ» Powered by Rust."
license = "MIT"
repository = "https://github.com/8ria/subslay"
readme = "README.md"
keywords = ["emoji", "text", "emoji-mapping", "natural-language"]
categories = ["text-processing", "command-line-utilities"]
include = [
  "src/**",
  "data/embeddings.bin",
  "Cargo.toml",
  "README.md",
]

[dependencies]
half = { version = "2.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
strsim = "0.11.1"
bincode = "1.3"

[profile.release]
opt-level = 3
lto = true
